[build]
  command = "ng build --configuration production && ng run sandbox-universal:serverless:production"
  publish = "dist/sandbox-universal/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"
